# Generated by Django 4.2.2 on 2023-06-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("last_read", models.DateTimeField(auto_created=True, auto_now=True)),
                (
                    "book_id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("book_name", models.CharField(max_length=200)),
                ("book_author", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=50)),
                ("tags", models.TextField()),
                ("last_read_page", models.CharField(max_length=100)),
            ],
        ),
    ]
