# Generated by Django 4.2.2 on 2023-06-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_book_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="last_read_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="total_page",
            field=models.IntegerField(default=0),
        ),
    ]
