# Generated by Django 4.2.2 on 2023-06-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_book_last_read_index_book_total_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookHighlight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("book_id", models.CharField(max_length=32)),
                ("page", models.CharField(max_length=100)),
                ("epubcfi", models.CharField(max_length=200)),
                ("highlight", models.TextField()),
                ("remark", models.TextField(null=True)),
            ],
        ),
    ]
