# Generated by Django 4.2.2 on 2023-06-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_bookhighlight"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookhighlight",
            name="last_time",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
