# Generated by Django 4.2.2 on 2023-06-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0005_bookhighlight_last_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookhighlight",
            name="highlight",
        ),
        migrations.RemoveField(
            model_name="bookhighlight",
            name="page",
        ),
        migrations.AddField(
            model_name="bookhighlight",
            name="method_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
